### ISSUE TITLE
[Bug Report] Timetable Display Error

### ISSUE THREAD

**Issue by EasonSYC** [Jason-Ying/countdown#1]
![Screenshot](https://user-images.githubusercontent.com/71219162/165069386-10c0b448-e8fc-4275-bc15-a099c9d60596.png)

**Comment by EasonSYC** [comment]
See the difference between the width of the line

**Comment by EasonSYC** [comment]
Should be a css style file problem.

**Comment by Jason-Ying** [comment]
@=

> See the difference between the width of the line

Failed to let the issue reappear. I will be grateful if you can provide more details of your device/browser.

**Comment by EasonSYC** [comment]
Currently using Safari 15.6 (17613.2.6.1.1) on macOS Monterey beta 12.4, however i believe it is not a issue caused by beta versions.

Only appearing in Class 4 Grade 10 (as of testing in Grade 10).

**Comment by EasonSYC** [comment]
Feature does not seem to appear in Chrome.

**Comment by Jason-Ying** [comment]
I used 'border="1"' to clarify the width of the lines in the table. Although VSCode does not quite like this 'border' and is turning it red for reasons I don't know, using 'border' seems to be working on all the widely used browsers. Except stupid Safari.
![image](https://user-images.githubusercontent.com/66516303/165075931-0c4c069f-d6ca-4a23-882a-dbe6d33facf2.png)

**Comment by EasonSYC** [comment]
Well, still not fixed after solving #2.

**Comment by EasonSYC** [comment]
But quite strange, this issue is not stable, may appear but may also disappear. I'll close this issue for now and will open a new one if reasons are found.
