### ISSUE TITLE
[Bug Report] Request of Unexisting Fonts (404)

### ISSUE THREAD

**Issue by EasonSYC** [Jason-Ying/countdown#2]
![Screenshot 2022-04-25 at 18 16 22](https://user-images.githubusercontent.com/71219162/165069954-a12d4d59-c2e6-4742-abc8-5933ea933891.png)

**Comment by Jason-Ying** [comment]
Actually the webpage is not using any of the icons in the fa-regular-400.* font pack, but considering its somehow potential relationship with #1 , I'll fix this shortly and please tell me whether it's been fixed by then.

**Comment by Jason-Ying** [comment]
Added. Please check if #1 has been fixed. @EasonSYC

**Comment by EasonSYC** [comment]
Well to be honest i would like to test, but do you have any idea why accessing the website is so slow

**Comment by EasonSYC** [comment]
I'm using 3 devices accessing but none of them seems to have 'none white-page' access

**Comment by Jason-Ying** [comment]
Actually using the webpage for the first time will turn out to be really slow, for its using some 'iframe's and wjx.com is slow for some reasons which I don't know. Further use will be sped up thanks to caches.

**Comment by EasonSYC** [comment]
> Added. Please check if #1 has been fixed. @EasonSYC

#1 is still appearing in Class 4 Grade 10 (Strange), but the 404 problem is fixed.
