### ISSUE TITLE
[Feature Request] Adding Sentences

### ISSUE THREAD

**Issue by EasonSYC** [Jason-Ying/countdown#4]
> 学习知识要善于思考、思考、再思考，我就是靠这个学习方法称为科学家的。——A. 爱因斯坦

> 我好像是一个在海滩上玩耍的小孩，不时地为捡到一个比通常更光滑的卵石或更好看的贝壳而感到高兴，但是，有待探索的真理的汪洋大海正展现在我的面前。——I. 牛顿

> 如果要跟随着理想而生活，本着真正自由的精神，勇往直前的毅力，诚实不自欺的思想而行，则定能臻于至美至善的境地。——居里夫人

> 没有昨日的基础科学，就没有今日的技术革命。——李政道

> 成功=艰苦的劳动+正确的途径+少说空话。在一个崇高的目的支持下，不停地工作，就会获得成功。——A. 爱因斯坦

> 研究物理学如同看一幅很大的画，近距离观察可以了解每一部分的细节，但还不够，你必须走到远处去观察整个画面，才能把握它的结构，更深入地理解它。——杨振宁

> 科学进展的最大祸害是故步自封，自我孤立。科学只有在充分的讨论中才会有进步。——L. 玻尔兹曼

> 给我最大快乐的，不是已获得的知识，而是不断地学习；不是已有的东西，而是不断地获取；不是已经达到的高度，而是继续不断地攀登。——高斯

> 一旦科学插上了幻想的翅膀，它就能赢得胜利。——M. 法拉第

> 对无知充分的清醒，才是知识真正发展的前奏曲。——J. 麦克斯韦

> 不登高山，不知天之高也；不临深溪，不知地之厚也。——荀子

> 铁不用就会生锈，水不流就会发臭，人的智慧不用就会枯萎。——达·芬奇

> 进步道路上的绊脚石是，也一向是不容怀疑的传统。——吴健雄

> 外部世界是我们所面对的、独立于我们而存在的绝对所在，而探索这些绝对所在所运用的规律，我认为就是最崇高的科学研究任务。——M. 普朗克

> 如果一个人掌握了他的学科的基础理论，并学会了独立思考与工作，他必定会找到自己的路，而且比起那些主要以获得细节知识为其训练内容的人来说，他一定会更好的适应进步和变化。——A. 爱因斯坦

> 人类总得不断地总结经验，有所发现，有所发明，有所创造，有所前进。停止的论点，悲观的论点，无所作为和骄傲自满的论点，都是错误的。——周恩来

> 中国落后于欧美，这是什么原因呢？我以为必须找出这个原因，因为如果我们不了解它，我们关于科学技术史的观点就处于混乱之中，如果我们不了解过去，也就没有多少希望掌握未来。——李约瑟

> 物理学史我们认识世界的基础……是其他科学和绝大部分技术发展的直接的或不可缺少的基础，物理学曾经是、现在是、将来也还会是全球技术和经济发展的主要驱动力。——第三次世界物理学大会（2000年12月15-16日，德国柏林）决议

摘自程守洙《普通物理学（第四版）》每章首的金句与绪论与总结。

**Comment by Jason-Ying** [comment]
Projected to add 6 out of 18 considering length. Thanks for sharing those meaningful and beautiful sentences.

**Comment by EasonSYC** [comment]
Will be my pleasure.

**Comment by Jason-Ying** [comment]
Added. Issue closed.
